- name: setup os x defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  notify:
    - "{{ item.notify }}"
  with_items:
    - "{{ osx_defaults }}"
- name: symbolic link
  file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ links }}"
- name: directory
  file:
    state: directory
    path: "{{ item.path }}"
  with_items:
    - "{{ dirs }}"

