homebrew_cask_packages:
  - { name: google-japanese-ime }
  - { name: google-chrome }
  - { name: visual-studio-code }
  - { name: adobe-acrobat-reader }
  - { name: zoom }
  - { name: dropbox }
  - { name: slack }
  - { name: rancher }
  - { name: discord }
