- block:
  - name: brew cask install
    command: brew install --cask "{{ item.name }}"
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
    # homebrew_cask:
    #   name: "{{ item.name }}"
    with_items: "{{ homebrew_cask_packages }}"

  tags:
    - homebrew_cask
