packages:
  - { name: wget }
  - { name: pyenv }
  - { name: nodenv }
  - { name: yarn }
  - { name: openssl }
  - { name: mas }
  - { name: awscli }
  - { name: fzf }
  - { name: docker }
  - { name: ffmpeg }
  - { name: jq }
  - { name: tree }
  - { name: pwgen }
